namespace Example
{
    partial class KeyboradExampleForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Keyboard.VirtualKbButton virtualKbButton48 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton49 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton50 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton51 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton52 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton53 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton54 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton55 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton56 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton57 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton58 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton59 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton60 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton61 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton62 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton63 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton64 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton65 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton66 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton67 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton68 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton69 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton70 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton71 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton72 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton73 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton74 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton75 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton76 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton77 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton78 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton79 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton80 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton81 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton82 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton83 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton84 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton85 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton86 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton87 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton88 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton89 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton90 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton91 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton92 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton93 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton94 = new Keyboard.VirtualKbButton();
            this.btn_RunNotepad = new System.Windows.Forms.Button();
            this.btn_RunWordPad = new System.Windows.Forms.Button();
            this.virtualKeyboard1 = new Keyboard.VirtualKeyboard();
            this.SuspendLayout();
            // 
            // btn_RunNotepad
            // 
            this.btn_RunNotepad.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.btn_RunNotepad.Location = new System.Drawing.Point(917, 177);
            this.btn_RunNotepad.Name = "btn_RunNotepad";
            this.btn_RunNotepad.Size = new System.Drawing.Size(102, 52);
            this.btn_RunNotepad.TabIndex = 9;
            this.btn_RunNotepad.Text = "Run notepad";
            this.btn_RunNotepad.UseVisualStyleBackColor = true;
            this.btn_RunNotepad.Click += new System.EventHandler(this.btn_RunNotepad_Click);
            // 
            // btn_RunWordPad
            // 
            this.btn_RunWordPad.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.btn_RunWordPad.Location = new System.Drawing.Point(917, 117);
            this.btn_RunWordPad.Name = "btn_RunWordPad";
            this.btn_RunWordPad.Size = new System.Drawing.Size(102, 52);
            this.btn_RunWordPad.TabIndex = 8;
            this.btn_RunWordPad.Text = "Run WordPad";
            this.btn_RunWordPad.UseVisualStyleBackColor = true;
            this.btn_RunWordPad.Click += new System.EventHandler(this.btn_RunWordPad_Click);
            // 
            // virtualKeyboard1
            // 
            this.virtualKeyboard1.AltGrState = false;
            this.virtualKeyboard1.AltState = false;
            this.virtualKeyboard1.BackColor = System.Drawing.Color.Transparent;
            this.virtualKeyboard1.BackgroundColor = System.Drawing.Color.White;
            this.virtualKeyboard1.BeginGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(206)))), ((int)(((byte)(241)))));
            this.virtualKeyboard1.BorderColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.ButtonBorderColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard1.ButtonRectRadius = 5;
            this.virtualKeyboard1.CapsLockState = false;
            this.virtualKeyboard1.ColorPressedState = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(145)))), ((int)(((byte)(78)))));
            this.virtualKeyboard1.CtrlState = false;
            this.virtualKeyboard1.DecimalSeparator = '.';
            this.virtualKeyboard1.Dock = System.Windows.Forms.DockStyle.Left;
            this.virtualKeyboard1.EndGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(170)))), ((int)(((byte)(230)))));
            virtualKbButton48.BottomFont = null;
            virtualKbButton48.BottomText = "`";
            virtualKbButton48.CanSendCommand = true;
            virtualKbButton48.Picture = null;
            virtualKbButton48.Tag = null;
            virtualKbButton48.TopFont = null;
            virtualKbButton48.TopText = "~";
            virtualKbButton49.BottomFont = null;
            virtualKbButton49.BottomText = "1";
            virtualKbButton49.CanSendCommand = true;
            virtualKbButton49.Picture = null;
            virtualKbButton49.Tag = null;
            virtualKbButton49.TopFont = null;
            virtualKbButton49.TopText = "!";
            virtualKbButton50.BottomFont = null;
            virtualKbButton50.BottomText = "2";
            virtualKbButton50.CanSendCommand = true;
            virtualKbButton50.Picture = null;
            virtualKbButton50.Tag = null;
            virtualKbButton50.TopFont = null;
            virtualKbButton50.TopText = "@";
            virtualKbButton51.BottomFont = null;
            virtualKbButton51.BottomText = "3";
            virtualKbButton51.CanSendCommand = true;
            virtualKbButton51.Picture = null;
            virtualKbButton51.Tag = null;
            virtualKbButton51.TopFont = null;
            virtualKbButton51.TopText = "#";
            virtualKbButton52.BottomFont = null;
            virtualKbButton52.BottomText = "4";
            virtualKbButton52.CanSendCommand = true;
            virtualKbButton52.Picture = null;
            virtualKbButton52.Tag = null;
            virtualKbButton52.TopFont = null;
            virtualKbButton52.TopText = "$";
            virtualKbButton53.BottomFont = null;
            virtualKbButton53.BottomText = "5";
            virtualKbButton53.CanSendCommand = true;
            virtualKbButton53.Picture = null;
            virtualKbButton53.Tag = null;
            virtualKbButton53.TopFont = null;
            virtualKbButton53.TopText = "%";
            virtualKbButton54.BottomFont = null;
            virtualKbButton54.BottomText = "6";
            virtualKbButton54.CanSendCommand = true;
            virtualKbButton54.Picture = null;
            virtualKbButton54.Tag = null;
            virtualKbButton54.TopFont = null;
            virtualKbButton54.TopText = "^";
            virtualKbButton55.BottomFont = null;
            virtualKbButton55.BottomText = "7";
            virtualKbButton55.CanSendCommand = true;
            virtualKbButton55.Picture = null;
            virtualKbButton55.Tag = null;
            virtualKbButton55.TopFont = null;
            virtualKbButton55.TopText = "&";
            virtualKbButton56.BottomFont = null;
            virtualKbButton56.BottomText = "8";
            virtualKbButton56.CanSendCommand = true;
            virtualKbButton56.Picture = null;
            virtualKbButton56.Tag = null;
            virtualKbButton56.TopFont = null;
            virtualKbButton56.TopText = "*";
            virtualKbButton57.BottomFont = null;
            virtualKbButton57.BottomText = "9";
            virtualKbButton57.CanSendCommand = true;
            virtualKbButton57.Picture = null;
            virtualKbButton57.Tag = null;
            virtualKbButton57.TopFont = null;
            virtualKbButton57.TopText = "(";
            virtualKbButton58.BottomFont = null;
            virtualKbButton58.BottomText = "0";
            virtualKbButton58.CanSendCommand = true;
            virtualKbButton58.Picture = null;
            virtualKbButton58.Tag = null;
            virtualKbButton58.TopFont = null;
            virtualKbButton58.TopText = ")";
            virtualKbButton59.BottomFont = null;
            virtualKbButton59.BottomText = "-";
            virtualKbButton59.CanSendCommand = true;
            virtualKbButton59.Picture = null;
            virtualKbButton59.Tag = null;
            virtualKbButton59.TopFont = null;
            virtualKbButton59.TopText = "_";
            virtualKbButton60.BottomFont = null;
            virtualKbButton60.BottomText = "+";
            virtualKbButton60.CanSendCommand = true;
            virtualKbButton60.Picture = null;
            virtualKbButton60.Tag = null;
            virtualKbButton60.TopFont = null;
            virtualKbButton60.TopText = "=";
            new Keyboard.ButtonsCollection().Add(virtualKbButton48);
            new Keyboard.ButtonsCollection().Add(virtualKbButton49);
            new Keyboard.ButtonsCollection().Add(virtualKbButton50);
            new Keyboard.ButtonsCollection().Add(virtualKbButton51);
            new Keyboard.ButtonsCollection().Add(virtualKbButton52);
            new Keyboard.ButtonsCollection().Add(virtualKbButton53);
            new Keyboard.ButtonsCollection().Add(virtualKbButton54);
            new Keyboard.ButtonsCollection().Add(virtualKbButton55);
            new Keyboard.ButtonsCollection().Add(virtualKbButton56);
            new Keyboard.ButtonsCollection().Add(virtualKbButton57);
            new Keyboard.ButtonsCollection().Add(virtualKbButton58);
            new Keyboard.ButtonsCollection().Add(virtualKbButton59);
            new Keyboard.ButtonsCollection().Add(virtualKbButton60);
            this.virtualKeyboard1.FontColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.FontColorShiftDisabled = System.Drawing.Color.DimGray;
            this.virtualKeyboard1.FontColorSpecialKey = System.Drawing.Color.DarkBlue;
            virtualKbButton61.BottomFont = null;
            virtualKbButton61.BottomText = "";
            virtualKbButton61.CanSendCommand = true;
            virtualKbButton61.Picture = null;
            virtualKbButton61.Tag = null;
            virtualKbButton61.TopFont = null;
            virtualKbButton61.TopText = "z";
            virtualKbButton62.BottomFont = null;
            virtualKbButton62.BottomText = "";
            virtualKbButton62.CanSendCommand = true;
            virtualKbButton62.Picture = null;
            virtualKbButton62.Tag = null;
            virtualKbButton62.TopFont = null;
            virtualKbButton62.TopText = "x";
            virtualKbButton63.BottomFont = null;
            virtualKbButton63.BottomText = "";
            virtualKbButton63.CanSendCommand = true;
            virtualKbButton63.Picture = null;
            virtualKbButton63.Tag = null;
            virtualKbButton63.TopFont = null;
            virtualKbButton63.TopText = "c";
            virtualKbButton64.BottomFont = null;
            virtualKbButton64.BottomText = "";
            virtualKbButton64.CanSendCommand = true;
            virtualKbButton64.Picture = null;
            virtualKbButton64.Tag = null;
            virtualKbButton64.TopFont = null;
            virtualKbButton64.TopText = "v";
            virtualKbButton65.BottomFont = null;
            virtualKbButton65.BottomText = "";
            virtualKbButton65.CanSendCommand = true;
            virtualKbButton65.Picture = null;
            virtualKbButton65.Tag = null;
            virtualKbButton65.TopFont = null;
            virtualKbButton65.TopText = "b";
            virtualKbButton66.BottomFont = null;
            virtualKbButton66.BottomText = "";
            virtualKbButton66.CanSendCommand = true;
            virtualKbButton66.Picture = null;
            virtualKbButton66.Tag = null;
            virtualKbButton66.TopFont = null;
            virtualKbButton66.TopText = "n";
            virtualKbButton67.BottomFont = null;
            virtualKbButton67.BottomText = "";
            virtualKbButton67.CanSendCommand = true;
            virtualKbButton67.Picture = null;
            virtualKbButton67.Tag = null;
            virtualKbButton67.TopFont = null;
            virtualKbButton67.TopText = "m";
            virtualKbButton68.BottomFont = null;
            virtualKbButton68.BottomText = ",";
            virtualKbButton68.CanSendCommand = true;
            virtualKbButton68.Picture = null;
            virtualKbButton68.Tag = null;
            virtualKbButton68.TopFont = null;
            virtualKbButton68.TopText = "<";
            virtualKbButton69.BottomFont = null;
            virtualKbButton69.BottomText = ".";
            virtualKbButton69.CanSendCommand = true;
            virtualKbButton69.Picture = null;
            virtualKbButton69.Tag = null;
            virtualKbButton69.TopFont = null;
            virtualKbButton69.TopText = ">";
            virtualKbButton70.BottomFont = null;
            virtualKbButton70.BottomText = "/";
            virtualKbButton70.CanSendCommand = true;
            virtualKbButton70.Picture = null;
            virtualKbButton70.Tag = null;
            virtualKbButton70.TopFont = null;
            virtualKbButton70.TopText = "?";
            new Keyboard.ButtonsCollection().Add(virtualKbButton61);
            new Keyboard.ButtonsCollection().Add(virtualKbButton62);
            new Keyboard.ButtonsCollection().Add(virtualKbButton63);
            new Keyboard.ButtonsCollection().Add(virtualKbButton64);
            new Keyboard.ButtonsCollection().Add(virtualKbButton65);
            new Keyboard.ButtonsCollection().Add(virtualKbButton66);
            new Keyboard.ButtonsCollection().Add(virtualKbButton67);
            new Keyboard.ButtonsCollection().Add(virtualKbButton68);
            new Keyboard.ButtonsCollection().Add(virtualKbButton69);
            new Keyboard.ButtonsCollection().Add(virtualKbButton70);
            this.virtualKeyboard1.IsNumeric = false;
            this.virtualKeyboard1.LabelFont = new System.Drawing.Font("Tahoma", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontShiftDisabled = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontSpecialKey = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LanguageButtonBottomText = "";
            this.virtualKeyboard1.LanguageButtonImage = null;
            this.virtualKeyboard1.LanguageButtonTopText = "";
            this.virtualKeyboard1.Location = new System.Drawing.Point(5, 5);
            this.virtualKeyboard1.Name = "virtualKeyboard1";
            this.virtualKeyboard1.NumLockState = false;
            virtualKbButton71.BottomFont = null;
            virtualKbButton71.BottomText = "";
            virtualKbButton71.CanSendCommand = true;
            virtualKbButton71.Picture = null;
            virtualKbButton71.Tag = null;
            virtualKbButton71.TopFont = null;
            virtualKbButton71.TopText = "q";
            virtualKbButton72.BottomFont = null;
            virtualKbButton72.BottomText = "";
            virtualKbButton72.CanSendCommand = true;
            virtualKbButton72.Picture = null;
            virtualKbButton72.Tag = null;
            virtualKbButton72.TopFont = null;
            virtualKbButton72.TopText = "w";
            virtualKbButton73.BottomFont = null;
            virtualKbButton73.BottomText = "";
            virtualKbButton73.CanSendCommand = true;
            virtualKbButton73.Picture = null;
            virtualKbButton73.Tag = null;
            virtualKbButton73.TopFont = null;
            virtualKbButton73.TopText = "e";
            virtualKbButton74.BottomFont = null;
            virtualKbButton74.BottomText = "";
            virtualKbButton74.CanSendCommand = true;
            virtualKbButton74.Picture = null;
            virtualKbButton74.Tag = null;
            virtualKbButton74.TopFont = null;
            virtualKbButton74.TopText = "r";
            virtualKbButton75.BottomFont = null;
            virtualKbButton75.BottomText = "";
            virtualKbButton75.CanSendCommand = true;
            virtualKbButton75.Picture = null;
            virtualKbButton75.Tag = null;
            virtualKbButton75.TopFont = null;
            virtualKbButton75.TopText = "t";
            virtualKbButton76.BottomFont = null;
            virtualKbButton76.BottomText = "";
            virtualKbButton76.CanSendCommand = true;
            virtualKbButton76.Picture = null;
            virtualKbButton76.Tag = null;
            virtualKbButton76.TopFont = null;
            virtualKbButton76.TopText = "y";
            virtualKbButton77.BottomFont = null;
            virtualKbButton77.BottomText = "";
            virtualKbButton77.CanSendCommand = true;
            virtualKbButton77.Picture = null;
            virtualKbButton77.Tag = null;
            virtualKbButton77.TopFont = null;
            virtualKbButton77.TopText = "u";
            virtualKbButton78.BottomFont = null;
            virtualKbButton78.BottomText = "";
            virtualKbButton78.CanSendCommand = true;
            virtualKbButton78.Picture = null;
            virtualKbButton78.Tag = null;
            virtualKbButton78.TopFont = null;
            virtualKbButton78.TopText = "i";
            virtualKbButton79.BottomFont = null;
            virtualKbButton79.BottomText = "";
            virtualKbButton79.CanSendCommand = true;
            virtualKbButton79.Picture = null;
            virtualKbButton79.Tag = null;
            virtualKbButton79.TopFont = null;
            virtualKbButton79.TopText = "o";
            virtualKbButton80.BottomFont = null;
            virtualKbButton80.BottomText = "";
            virtualKbButton80.CanSendCommand = true;
            virtualKbButton80.Picture = null;
            virtualKbButton80.Tag = null;
            virtualKbButton80.TopFont = null;
            virtualKbButton80.TopText = "p";
            virtualKbButton81.BottomFont = null;
            virtualKbButton81.BottomText = "[";
            virtualKbButton81.CanSendCommand = true;
            virtualKbButton81.Picture = null;
            virtualKbButton81.Tag = null;
            virtualKbButton81.TopFont = null;
            virtualKbButton81.TopText = "{";
            virtualKbButton82.BottomFont = null;
            virtualKbButton82.BottomText = "]";
            virtualKbButton82.CanSendCommand = true;
            virtualKbButton82.Picture = null;
            virtualKbButton82.Tag = null;
            virtualKbButton82.TopFont = null;
            virtualKbButton82.TopText = "}";
            virtualKbButton83.BottomFont = null;
            virtualKbButton83.BottomText = "\\";
            virtualKbButton83.CanSendCommand = true;
            virtualKbButton83.Picture = null;
            virtualKbButton83.Tag = null;
            virtualKbButton83.TopFont = null;
            virtualKbButton83.TopText = "|";
            new Keyboard.ButtonsCollection().Add(virtualKbButton71);
            new Keyboard.ButtonsCollection().Add(virtualKbButton72);
            new Keyboard.ButtonsCollection().Add(virtualKbButton73);
            new Keyboard.ButtonsCollection().Add(virtualKbButton74);
            new Keyboard.ButtonsCollection().Add(virtualKbButton75);
            new Keyboard.ButtonsCollection().Add(virtualKbButton76);
            new Keyboard.ButtonsCollection().Add(virtualKbButton77);
            new Keyboard.ButtonsCollection().Add(virtualKbButton78);
            new Keyboard.ButtonsCollection().Add(virtualKbButton79);
            new Keyboard.ButtonsCollection().Add(virtualKbButton80);
            new Keyboard.ButtonsCollection().Add(virtualKbButton81);
            new Keyboard.ButtonsCollection().Add(virtualKbButton82);
            new Keyboard.ButtonsCollection().Add(virtualKbButton83);
            this.virtualKeyboard1.ShadowColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard1.ShadowShift = 6;
            this.virtualKeyboard1.ShiftState = false;
            this.virtualKeyboard1.ShowAlt = true;
            this.virtualKeyboard1.ShowArrowKeys = true;
            this.virtualKeyboard1.ShowBackground = true;
            this.virtualKeyboard1.ShowCtrl = true;
            this.virtualKeyboard1.ShowDeleteKey = true;
            this.virtualKeyboard1.ShowFunctionButtons = true;
            this.virtualKeyboard1.ShowLanguageButton = true;
            this.virtualKeyboard1.ShowNumericButtons = true;
            this.virtualKeyboard1.ShowTab = true;
            this.virtualKeyboard1.Size = new System.Drawing.Size(906, 364);
            this.virtualKeyboard1.TabIndex = 0;
            this.virtualKeyboard1.Text = "virtualKeyboard1";
            virtualKbButton84.BottomFont = null;
            virtualKbButton84.BottomText = "";
            virtualKbButton84.CanSendCommand = true;
            virtualKbButton84.Picture = null;
            virtualKbButton84.Tag = null;
            virtualKbButton84.TopFont = null;
            virtualKbButton84.TopText = "a";
            virtualKbButton85.BottomFont = null;
            virtualKbButton85.BottomText = "";
            virtualKbButton85.CanSendCommand = true;
            virtualKbButton85.Picture = null;
            virtualKbButton85.Tag = null;
            virtualKbButton85.TopFont = null;
            virtualKbButton85.TopText = "s";
            virtualKbButton86.BottomFont = null;
            virtualKbButton86.BottomText = "";
            virtualKbButton86.CanSendCommand = true;
            virtualKbButton86.Picture = null;
            virtualKbButton86.Tag = null;
            virtualKbButton86.TopFont = null;
            virtualKbButton86.TopText = "d";
            virtualKbButton87.BottomFont = null;
            virtualKbButton87.BottomText = "";
            virtualKbButton87.CanSendCommand = true;
            virtualKbButton87.Picture = null;
            virtualKbButton87.Tag = null;
            virtualKbButton87.TopFont = null;
            virtualKbButton87.TopText = "f";
            virtualKbButton88.BottomFont = null;
            virtualKbButton88.BottomText = "";
            virtualKbButton88.CanSendCommand = true;
            virtualKbButton88.Picture = null;
            virtualKbButton88.Tag = null;
            virtualKbButton88.TopFont = null;
            virtualKbButton88.TopText = "g";
            virtualKbButton89.BottomFont = null;
            virtualKbButton89.BottomText = "";
            virtualKbButton89.CanSendCommand = true;
            virtualKbButton89.Picture = null;
            virtualKbButton89.Tag = null;
            virtualKbButton89.TopFont = null;
            virtualKbButton89.TopText = "h";
            virtualKbButton90.BottomFont = null;
            virtualKbButton90.BottomText = "";
            virtualKbButton90.CanSendCommand = true;
            virtualKbButton90.Picture = null;
            virtualKbButton90.Tag = null;
            virtualKbButton90.TopFont = null;
            virtualKbButton90.TopText = "j";
            virtualKbButton91.BottomFont = null;
            virtualKbButton91.BottomText = "";
            virtualKbButton91.CanSendCommand = true;
            virtualKbButton91.Picture = null;
            virtualKbButton91.Tag = null;
            virtualKbButton91.TopFont = null;
            virtualKbButton91.TopText = "k";
            virtualKbButton92.BottomFont = null;
            virtualKbButton92.BottomText = "";
            virtualKbButton92.CanSendCommand = true;
            virtualKbButton92.Picture = null;
            virtualKbButton92.Tag = null;
            virtualKbButton92.TopFont = null;
            virtualKbButton92.TopText = "l";
            virtualKbButton93.BottomFont = null;
            virtualKbButton93.BottomText = ";";
            virtualKbButton93.CanSendCommand = true;
            virtualKbButton93.Picture = null;
            virtualKbButton93.Tag = null;
            virtualKbButton93.TopFont = null;
            virtualKbButton93.TopText = ":";
            virtualKbButton94.BottomFont = null;
            virtualKbButton94.BottomText = "\'";
            virtualKbButton94.CanSendCommand = true;
            virtualKbButton94.Picture = null;
            virtualKbButton94.Tag = null;
            virtualKbButton94.TopFont = null;
            virtualKbButton94.TopText = "\"";
            new Keyboard.ButtonsCollection().Add(virtualKbButton84);
            new Keyboard.ButtonsCollection().Add(virtualKbButton85);
            new Keyboard.ButtonsCollection().Add(virtualKbButton86);
            new Keyboard.ButtonsCollection().Add(virtualKbButton87);
            new Keyboard.ButtonsCollection().Add(virtualKbButton88);
            new Keyboard.ButtonsCollection().Add(virtualKbButton89);
            new Keyboard.ButtonsCollection().Add(virtualKbButton90);
            new Keyboard.ButtonsCollection().Add(virtualKbButton91);
            new Keyboard.ButtonsCollection().Add(virtualKbButton92);
            new Keyboard.ButtonsCollection().Add(virtualKbButton93);
            new Keyboard.ButtonsCollection().Add(virtualKbButton94);
            this.virtualKeyboard1.ButtonClick += new Keyboard.VirtualKeyboard.KeyboardButtonEventHandler(this.virtualKeyboard1_KeyboardButtonPressed);
            // 
            // KeyboradExampleForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1027, 374);
            this.Controls.Add(this.btn_RunNotepad);
            this.Controls.Add(this.btn_RunWordPad);
            this.Controls.Add(this.virtualKeyboard1);
            this.Name = "KeyboradExampleForm";
            this.Padding = new System.Windows.Forms.Padding(5);
            this.Text = "Keyborad Example";
            this.Load += new System.EventHandler(this.KeyboradExampleForm_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button btn_RunNotepad;
        private System.Windows.Forms.Button btn_RunWordPad;
        private Keyboard.VirtualKeyboard virtualKeyboard1;

    }
}